version: "3.9"

name: parsec

services:
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    command: parsec scheduler
    container_name: parsec-scheduler
    environment:
      PARSEC_DEBUG: true
      PARSEC_SCHEDULER_FLEETS: docker
      PARSEC_TELEMETRY_HOST: 0.0.0.0
      PARSEC_TELEMETRY_PORT: 6666
      PARSEC_DATABASE_HOST: postgres
      PARSEC_DATABASE_NAME: parsec_docker
      PARSEC_DATABASE_PASSWORD: password
      PARSEC_DATABASE_USER: parsec_docker
    depends_on:
      postgres:
        condition: service_healthy

  server-1:
    build:
      context: .
      dockerfile: Dockerfile
    command: parsec server dht
    container_name: parsec-server-1
    environment:
      AWS_REGION: docker
      PARSEC_DEBUG: true
      PARSEC_TELEMETRY_HOST: 0.0.0.0
      PARSEC_TELEMETRY_PORT: 6667
      PARSEC_SERVER_SERVER_HOST: server-1
      PARSEC_SERVER_SERVER_PORT: 7070
      PARSEC_SERVER_FLEET: docker
      PARSEC_SERVER_STARTUP_DELAY: 10s
      PARSEC_DATABASE_HOST: postgres
      PARSEC_DATABASE_NAME: parsec_docker
      PARSEC_DATABASE_PASSWORD: password
      PARSEC_DATABASE_USER: parsec_docker
    depends_on:
      postgres:
        condition: service_healthy

  server-2:
    build:
      context: .
      dockerfile: Dockerfile
    command: parsec server dht
    container_name: parsec-server-2
    environment:
      AWS_REGION: docker
      PARSEC_DEBUG: true
      PARSEC_TELEMETRY_HOST: 0.0.0.0
      PARSEC_TELEMETRY_PORT: 6667
      PARSEC_SERVER_SERVER_HOST: server-2
      PARSEC_SERVER_SERVER_PORT: 7070
      PARSEC_SERVER_FLEET: docker
      PARSEC_SERVER_STARTUP_DELAY: 10s
      PARSEC_DATABASE_HOST: postgres
      PARSEC_DATABASE_NAME: parsec_docker
      PARSEC_DATABASE_PASSWORD: password
      PARSEC_DATABASE_USER: parsec_docker
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14
    container_name: parsec-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U parsec_docker"]
      interval: 2s
      timeout: 2s
      retries: 5
    environment:
      POSTGRES_USER: parsec_docker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: parsec_docker