output   = "pkg/models"
wipe     = true

[psql]
dbname = "parsec"
host = "localhost"
port = 5432
user = "parsec"
pass = "password"
sslmode = "disable"
blacklist = ["schema_migrations", "runs", "nodes", "retrievals", "provides"]

[aliases.tables.schedulers_ecs]
up_plural     = "Schedulers"
up_singular   = "Scheduler"
down_plural   = "schedulers"
down_singular = "scheduler"

[aliases.tables.nodes_ecs]
up_plural     = "Nodes"
up_singular   = "Node"
down_plural   = "nodes"
down_singular = "node"

[aliases.tables.retrievals_ecs]
up_plural     = "Retrievals"
up_singular   = "Retrieval"
down_plural   = "retrievals"
down_singular = "retrieval"

[aliases.tables.provides_ecs]
up_plural     = "Provides"
up_singular   = "Provide"
down_plural   = "provides"
down_singular = "provide"