// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	NodesEcs      string
	ProvidesEcs   string
	RetrievalsEcs string
}{
	NodesEcs:      "nodes_ecs",
	ProvidesEcs:   "provides_ecs",
	RetrievalsEcs: "retrievals_ecs",
}
