// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	NodesEcs      string
	ProvidesEcs   string
	RetrievalsEcs string
	SchedulersEcs string
}{
	NodesEcs:      "nodes_ecs",
	ProvidesEcs:   "provides_ecs",
	RetrievalsEcs: "retrievals_ecs",
	SchedulersEcs: "schedulers_ecs",
}
